New folder structure
ResearchHub/researchhub-web pull request #1468
Opened 2023-06-21 21:12 UTC by lightninglu10

Folder structure for reference manager

![Screen Shot 2023-06-22 at 1 56 43 PM](https://github.com/ResearchHub/researchhub-web/assets/2453737/79f18735-98fc-438c-83e7-5fb94533b1b2)

2023-06-22 21:43 UTC, calvinhlee23 requested changes
Code looks good overall. Made a small comment.
But honestly, I'm not sure how i feel about the UI. 
I'm not really liking the UX in creating a folder and not being able to what kind of citations are there within child projects without having to click to parent than to child.

2023-06-22 21:43 UTC, calvinhlee23 commented on components/ReferenceManager/references/reference_organizer/ReferenceProjectsUpsertModal.tsx
>        project_name: nullthrows(projectName, "Project name may not be null"),
```suggestion
     project: upsertPurpose === "update" ? projectID : null, 
     parent: upsertPurpose === "update" ? null : parent
      is_public: isPublic,
      organization: currentOrg?.id,
      project_name: nullthrows(projectName, "Project name may not be null"),
```

2023-06-22 21:43 UTC, calvinhlee23 commented on components/ReferenceManager/references/reference_organizer/ReferenceProjectsUpsertModal.tsx
> +    }
Are we confident that creating a project will always have an active current project?
Not a fan of if statements like this that mutate already existing objects either. 
Can we do something like what i suggested in above?

2023-06-22 21:43 UTC, calvinhlee23 commented on components/ReferenceManager/references/reference_organizer/context/ReferenceActiveProjectContext.tsx
> +  currentOrgProjects: ProjectValue[];
nice

2023-06-22 21:43 UTC, calvinhlee23 commented on components/ReferenceManager/references/ReferencesContainer.tsx
> +
what is this :o

2023-06-22 21:44 UTC, calvinhlee23 commented on components/ReferenceManager/references/ReferencesContainer.tsx
> +  const pluralize = ({ text, length }) => {
can we make a separate file out side.

2023-06-23 01:42 UTC, yattias approved these changes

2023-06-23 01:42 UTC, yattias commented on components/ReferenceManager/references/api/updateReferenceCitation.ts
Small: If possible, small change is to add "Api" Suffice to both filename and method. That way - it is easier to understand it is doing an "api thing"

2023-06-23 01:42 UTC, yattias commented on components/ReferenceManager/references/reference_table/ReferencesTable.tsx
> +      onError: () => {},
Can we add a `captureEvent` call in here? I think these call will be helpful insights.

```
captureEvent({ msg: "Failed to move folder", error, data: {
  rowDragged,
  moveToFolderId,
  data,
}})
```

2023-06-23 17:12 UTC, calvinhlee23 approved these changes

2023-06-23 17:28 UTC, merged